apiVersion: v1
kind: Pod
metadata:
  name: my-special-pod
  labels:
    app: my-special-app
spec:
  containers:
  - name: my-special-container
    image: nginxinc/nginx-unprivileged:latest
    ports:
      - name: http
        containerPort: 8080
        protocol: TCP
    readinessProbe:
      httpGet:
        path: /
        port: http
        scheme: HTTP
      timeoutSeconds: 1
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
    livenessProbe:
      httpGet:
        path: /
        port: 8081
        scheme: HTTP
      timeoutSeconds: 1
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
