apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prd-

commonLabels:
  environment: production

resources:
  - ../../base

patches:
  - path: deployment.yaml
  - path: route.yaml
