apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configMap.yaml
- deployment.yaml
- route.yaml
- service.yaml
namePrefix: demo-
commonLabels:
  app: the-app
  owner: This Guy
